### ISSUE TITLE
urllib.parse problem

### ISSUE THREAD

**Issue by fychao** [yudazilian/SunnyJudge#1]
I think you want to serialize url, use as alternative will be better for latest python env.
```
from urllib import urlencode
```

**Comment by 0xyd** [comment]
It's very appreciate for your suggestion! However, the package's default python version is 3.3+.

In python 3.3+, the urlencode function belongs to urllib.parse. Therefore, I have to use 
```
from urllib import parse
``` 

However, you remind me that it is somehow better to import urlencode method as below:
```
from urllib.parse import urlencode
```

I will rewrite it recently. Hope you like this package. :)
